# Generated by Django 5.1.4 on 2025-01-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='client_photos/')),
                ('review_text', models.TextField()),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 звезд'), (2, '2 звезд'), (3, '3 звезд'), (4, '4 звезд'), (5, '5 звезд')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'builder_review',
            },
        ),
    ]
